name: Test

on:
  push:
    branches: [ "!main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 22.2.0
      uses: actions/setup-node@v3
      with:
        node-version: 22.2.0
        cache: 'npm'
    - run: npm install
    - run: npm run compile
    - run: npm run export-satisfactory-data
    - run: npm run build-app-prod
